server:
  port: 8888
spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/my_blog?useUnicode=true&characterEncoding=utf8
     username: root
     password: 123
     hikari:
       maximum-pool-size: 10
       max-lifetime: 1765000
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix:
      classpath: /templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html # ;charset=<encoding> is added
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
logging:
  level:
    org.springframework.web: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
security:
  basic:
    enabled: false